### ISSUE TITLE
wrong handle of arrow up/down, also handle space key

### ISSUE THREAD

**Issue by moseschrist** [moseschrist/consoleproject#11]
regarding #10 you do not handle arrows correctly, arrow up down should show a sign that your are one of the items (see how i did it in combobox, i switched foreground and background) and the space button should select / de-select an item on the checkbox.
same goes for #8

**Comment by amitresh** [comment]
Asaf ... please sync on my updates and re-check. Should be good now.

My plan is to use this checkbox class to implement a RadioBoxList according to a setting, like Michael suggested ... and then get rid of the original RadioBox class. So we will have a generic CheckList control that can have a "SingleSelection" or "MultipleSelection" attribute.

**Comment by moseschrist** [comment]
great !
