### ISSUE TITLE
Textbox bugs

### ISSUE THREAD

**Issue by amitresh** [moseschrist/consoleproject#13]
In an empty field, move the cursor with the arrow keys or with the mouse pointer to the middle of empty space. Enter a keystroke ... Program explodes ...
(I don't know how to link this comment to a branch ...)

**Comment by amitresh** [comment]
Now the textbox does not accept blanks in its input. Can't I enter 2 separated words?

**Comment by moseschrist** [comment]
The space button does not work ?

**Comment by moseschrist** [comment]
Should we also implement tab key ?

**Comment by amitresh** [comment]
I think that the TAB key should progress the Focus to the next controller.
So the TAB key should be something that a controller responds as NOT_MINE
... and the manager shifts the focus (according to some logic)

Amit

On Fri, Feb 12, 2016 at 11:40 AM, moseschrist <notifications@github.com>
wrote:

> Should we also implement tab key ?
>
> On Feb 12, 2016 11:25 AM, "asaf algawi" <asaf.algawi@gmail.com> wrote:
>
> > The space button does not work ?
> > On Feb 12, 2016 11:09 AM, "Amit" <notifications@github.com> wrote:
> >
> >> Now the textbox does not accept blanks in its input. Can't I enter 2
> >> separated words?
> >>
> >> —
> >> Reply to this email directly or view it on GitHub
> >> <
> https://github.com/moseschrist/consoleproject/issues/13#issuecomment-183244297
> >
> >> .
> >>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/moseschrist/consoleproject/issues/13#issuecomment-183253121>
> .
>



-- 
-------------------------------
Amit Resh
Software Engineering
*Shenkar*

**Comment by moseschrist** [comment]
using that logic, tab should be responded as "return_to_parent"
it's the parent job to move to focus to another sibling.

**Comment by moseschrist** [comment]
fixed blank space issue. plz verify.

**Comment by amitresh** [comment]
Now I can crash it again by using the mouse to position the cursor beyond the last visible char and hitting the keyboard:
Do this: fill the entire field; backspace; position with mouse beyond the lst char; hit keyboard.

**Comment by moseschrist** [comment]
I don't think of it as a valid solution. It seems like an easy way out

**Comment by amitresh** [comment]
Not sure I understand your reply.

You agree this is a bug, right?
How hard can it be to correct it?

On Fri, Feb 12, 2016 at 7:39 PM, moseschrist <notifications@github.com>
wrote:

> I don't think of it as a valid solution. It seems like an easy way out
> On Feb 12, 2016 6:30 PM, "Amit" <notifications@github.com> wrote:
>
> > Now I can crash it again by using the mouse to position the cursor beyond
> > the last visible char and hitting the keyboard:
> > Do this: fill the entire field; backspace; position with mouse beyond the
> > lst char; hit keyboard.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/moseschrist/consoleproject/issues/13#issuecomment-183398729
> >
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/moseschrist/consoleproject/issues/13#issuecomment-183425164>
> .
>



-- 
-------------------------------
Amit Resh
Software Engineering
*Shenkar*

**Comment by moseschrist** [comment]
no, of course it's a bug :)
commiting a fix for it now.

**Comment by amitresh** [comment]
OK. Now it's perfect. Feel free to merge into Master
