### ISSUE TITLE
Comments regarding #12

### ISSUE THREAD

**Issue by amitresh** [moseschrist/consoleproject#17]
Logic works OK now.

The cursor still stays on when this control has focus.

I took care of this by introducing the virtual SetFocus() releaseFocus() routines in IControl. Then each implementation can decide what to there in its case. the ComboBox should make the cursor invisible (like the checkbox). But this can be done after the merge ... so these 2 virtual functions get into IControl.

**Comment by moseschrist** [comment]
i believe i did not understand your the issue, did you wish me to remove to
cursor in the drop down menu or in the "textbox" itself ?

**Comment by amitresh** [comment]
I think the ComboBox should work like this:
1. Upper level moves Focus to a ComboBox ==>
    A. The field (and possibly its current value) are highlighted
    B. Cursor made invisible
2. User presses ENTER or uses mouse to click the 'V'
   A. Menu drops down
   B. current selection is highlighted
3. Up/Down keys scroll through options
4. Enter/Mouse-click can select a new option
    A. Option is displayed in field
    B. Dropdown menu folded away
5. Focused taken away from ComboBox
    A. Field value displayed in normal video
    B. Cursor state from before focus was given re-instated

I added 2 virtual functions to IControl.h:
	virtual void setFocus(){}
	virtual void releaseFocus(){}

My checkBox implements these with the cursor under the assumption that the upper-level will call them for each controller in turn. After we all merge, you can use them in the same way.

**Comment by moseschrist** [comment]
ok

**Comment by amitresh** [comment]
One additional .... we also decided to separate the key/mouse event handling to functions .. so we don't have 2 embedded switch statements

**Comment by moseschrist** [comment]
We shall do it in refactoring.

**Comment by amitresh** [comment]
OK
