### ISSUE TITLE
wrong interpretation of non ascii chars

### ISSUE THREAD

**Issue by moseschrist** [moseschrist/consoleproject#5]
#3 You accept all kinds of non-ASCII keystrokes as if they are charachters. for example: SHIFT, CTRL, INS etc. All of these are accepted as displayable charachters

**Comment by amitresh** [comment]
Now you don't respond to digits coming from the numeric-keypad (when Num-Lock is ON)

**Comment by moseschrist** [comment]
are you sure ? it seems to work for me.

**Comment by moseschrist** [comment]
please review again, i fixed the numpad handling.

**Comment by amitresh** [comment]
OK
